### ISSUE TITLE
buildMap broken when images don't have C, Z, T dimensions

### ISSUE THREAD

**Issue by zjniu** [Kitware/UPennContrast#210]
When an image does not have channels, z-levels, or multiple time points, the buildMap function errors out. This occurs for both annotation and property workers. An example is shown below:
```
Traceback (most recent call last):

  File "/entrypoint.py", line 160, in <module>

    main(args.datasetId, args.apiUrl, args.token, json.loads(args.parameters))

  File "/entrypoint.py", line 93, in main

    datasetClient = tiles.UPennContrastDataset(

  File "/UPennContrast/devops/girder/annotation_client/annotation_client/tiles.py", line 32, in __init__

    self.map = self.buildMap(self.tiles.get('frames', None))

  File "/UPennContrast/devops/girder/annotation_client/annotation_client/tiles.py", line 49, in buildMap

    Z = frame['IndexZ']

KeyError: 'IndexZ'

ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python3', '/entrypoint.py', '--apiUrl', 'http://localhost:8080/api/v1', '--token', 'XHfa3HaZO9cMT4g5IKGOGmluIo7WCxmgZzDJNMm5T8guZz8FuqnIGTJ7xFae9HOC', '--parameters', '{"id": "Point Intensity", "name": "Point Intensity", "image": "boucaud/point_intensity_worker:latest", "propertyType": "layer", "layer": 0, "tags": {"exclusive": false, "tags": []}, "independant": false, "shape": null, "enabled": true, "computed": false, "customName": null, "channel": 0, "workerInterface": {}}', '--datasetId', '624b14838c7d5bd086824aef']' command failed.  (See above for error)
```

**Comment by zjniu** [comment]
@boucaud When do you think this can be fixed? I cannot make any further progress with workers without this working.
